tree:
  segue1: "Want to help Rocky Linux? Tell me..."
  segue2: "what's your area of interest?"
  options:
    - id: "design"
      title: "DESIGN!"
      subtitle: "pixel ninjas"
      options:
        - id: "websites"
          title: "Website Design"
          subtitle: "crafting user experiences"
          link: "https://github.com/rocky-linux/rockylinux.org"
        - id: "graphics"
          title: "Graphics Design"
          subtitle: "visual storytelling"
          link: "https://chat.rockylinux.org/rocky-linux/channels/design"
        - id: "ux"
          title: "UX Design"
          subtitle: "making things intuitive"
          link: "https://chat.rockylinux.org/rocky-linux/channels/ux"

    - id: "coding"
      title: "CODING"
      subtitle: "hacking the gibson"
      options:
        - id: "web-dev"
          title: "Web Development"
          subtitle: "building the web presence"
          link: "https://github.com/rocky-linux/rockylinux.org"
        - id: "system"
          title: "System Programming"
          subtitle: "core system development"
          link: "https://github.com/rocky-linux/rocky"
        - id: "automation"
          title: "Automation"
          subtitle: "making things efficient"
          link: "https://github.com/rocky-linux/ansible-role-rocky-tools"

    - id: "documentation"
      title: "DOCUMENTATION"
      subtitle: "wordsmithery"
      options:
        - id: "technical-writing"
          title: "Technical Writing"
          subtitle: "explaining the complex"
          link: "https://github.com/rocky-linux/documentation"
        - id: "translation"
          title: "Translation"
          subtitle: "breaking language barriers"
          link: "https://chat.rockylinux.org/rocky-linux/channels/translation"

    - id: "community"
      title: "COMMUNITY"
      subtitle: "connecting the dots"
      options:
        - id: "advocacy"
          title: "Advocacy"
          subtitle: "spreading the word"
          link: "https://chat.rockylinux.org/rocky-linux/channels/community"
        - id: "support"
          title: "User Support"
          subtitle: "helping others succeed"
          link: "https://chat.rockylinux.org/rocky-linux/channels/support"
        - id: "events"
          title: "Event Organization"
          subtitle: "bringing people together"
          link: "https://chat.rockylinux.org/rocky-linux/channels/events"

    - id: "qa"
      title: "TESTING"
      subtitle: "if it's not tested, it's broken"
      options:
        - id: "bug-hunting"
          title: "Bug Hunting"
          subtitle: "finding the glitches"
          link: "https://github.com/rocky-linux/rocky/issues"
        - id: "test-automation"
          title: "Test Automation"
          subtitle: "automated quality assurance"
          link: "https://github.com/rocky-linux/testing"

    - id: "packaging"
      title: "PACKAGING"
      subtitle: "building the distribution"
      options:
        - id: "rpm-packaging"
          title: "RPM Packaging"
          subtitle: "creating packages"
          link: "https://github.com/rocky-linux/rpms"
        - id: "module-building"
          title: "Module Building"
          subtitle: "composing the distro"
          link: "https://chat.rockylinux.org/rocky-linux/channels/packaging"
    # Add more categories... 