tree:
  segueKey1: "Want to help Rocky Linux? Tell me..."
  segueKey2: "What's your area of interest?"
  options:
    - id: "design"
      titleKey: "questions.design.title"
      subtitleKey: "questions.design.subtitle"
      options:
        - id: "websites"
          titleKey: "questions.design.websites.title"
          subtitleKey: "questions.design.websites.subtitle"
          link: "https://github.com/rocky-linux/rockylinux.org"
        - id: "graphics"
          titleKey: "questions.design.graphics.title"
          subtitleKey: "questions.design.graphics.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/design"
        - id: "ux"
          titleKey: "questions.design.ux.title"
          subtitleKey: "questions.design.ux.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/ux"

    - id: "coding"
      titleKey: "questions.coding.title"
      subtitleKey: "questions.coding.subtitle"
      options:
        - id: "web-dev"
          titleKey: "questions.coding.webdev.title"
          subtitleKey: "questions.coding.webdev.subtitle"
          link: "https://github.com/rocky-linux/rockylinux.org"
        - id: "system"
          titleKey: "questions.coding.system.title"
          subtitleKey: "questions.coding.system.subtitle"
          link: "https://github.com/rocky-linux/rocky"
        - id: "automation"
          titleKey: "questions.coding.automation.title"
          subtitleKey: "questions.coding.automation.subtitle"
          link: "https://github.com/rocky-linux/ansible-role-rocky-tools"

    - id: "documentation"
      titleKey: "questions.documentation.title"
      subtitleKey: "questions.documentation.subtitle"
      options:
        - id: "technical-writing"
          titleKey: "questions.documentation.technical.title"
          subtitleKey: "questions.documentation.technical.subtitle"
          link: "https://github.com/rocky-linux/documentation"
        - id: "translation"
          titleKey: "questions.documentation.translation.title"
          subtitleKey: "questions.documentation.translation.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/translation"

    - id: "community"
      titleKey: "questions.community.title"
      subtitleKey: "questions.community.subtitle"
      options:
        - id: "advocacy"
          titleKey: "questions.community.advocacy.title"
          subtitleKey: "questions.community.advocacy.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/community"
        - id: "support"
          titleKey: "questions.community.support.title"
          subtitleKey: "questions.community.support.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/support"
        - id: "events"
          titleKey: "questions.community.events.title"
          subtitleKey: "questions.community.events.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/events"

    - id: "qa"
      titleKey: "questions.qa.title"
      subtitleKey: "questions.qa.subtitle"
      options:
        - id: "bug-hunting"
          titleKey: "questions.qa.bugHunting.title"
          subtitleKey: "questions.qa.bugHunting.subtitle"
          link: "https://github.com/rocky-linux/rocky/issues"
        - id: "test-automation"
          titleKey: "questions.qa.testAutomation.title"
          subtitleKey: "questions.qa.testAutomation.subtitle"
          link: "https://github.com/rocky-linux/testing"

    - id: "packaging"
      titleKey: "questions.packaging.title"
      subtitleKey: "questions.packaging.subtitle"
      options:
        - id: "rpm-packaging"
          titleKey: "questions.packaging.rpm.title"
          subtitleKey: "questions.packaging.rpm.subtitle"
          link: "https://github.com/rocky-linux/rpms"
        - id: "module-building"
          titleKey: "questions.packaging.modules.title"
          subtitleKey: "questions.packaging.modules.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/packaging"
    # Add more categories... 