tree:
  segueKey1: "Want to help Rocky Linux? Tell me..."
  segueKey2: "What's your area of interest?"
  options:
    - id: "design"
      titleKey: "questions.design.title"
      subtitleKey: "questions.design.subtitle"
      options:
        - id: "websites"
          titleKey: "questions.design.websites.title"
          subtitleKey: "questions.design.websites.subtitle"
          link: "https://github.com/rocky-linux/rockylinux.org"
        - id: "graphics"
          titleKey: "questions.design.graphics.title"
          subtitleKey: "questions.design.graphics.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/design"
        - id: "ux"
          titleKey: "questions.design.ux.title"
          subtitleKey: "questions.design.ux.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/ux"

    - id: "coding"
      titleKey: "questions.coding.title"
      subtitleKey: "questions.coding.subtitle"
      options:
        - id: "web-dev"
          titleKey: "questions.coding.webdev.title"
          subtitleKey: "questions.coding.webdev.subtitle"
          link: "https://github.com/rocky-linux/rockylinux.org"
        - id: "system"
          titleKey: "questions.coding.system.title"
          subtitleKey: "questions.coding.system.subtitle"
          link: "https://github.com/rocky-linux/rocky"
        - id: "automation"
          titleKey: "questions.coding.automation.title"
          subtitleKey: "questions.coding.automation.subtitle"
          link: "https://github.com/rocky-linux/ansible-role-rocky-tools"

    - id: "documentation"
      titleKey: "questions.documentation.title"
      subtitleKey: "questions.documentation.subtitle"
      options:
        - id: "technical-writing"
          titleKey: "questions.documentation.technical.title"
          subtitleKey: "questions.documentation.technical.subtitle"
          link: "https://github.com/rocky-linux/documentation"
        - id: "translation"
          titleKey: "questions.documentation.translation.title"
          subtitleKey: "questions.documentation.translation.subtitle"
          link: "https://chat.rockylinux.org/rocky-linux/channels/translation"

    - id: "community"
      titleKey: "questions.community.title"
      subtitleKey: "questions.community.subtitle"
      options:
        - id: "advocacy"
          title: "Advocacy"
          subtitle: "spreading the word"
          link: "https://chat.rockylinux.org/rocky-linux/channels/community"
        - id: "support"
          title: "User Support"
          subtitle: "helping others succeed"
          link: "https://chat.rockylinux.org/rocky-linux/channels/support"
        - id: "events"
          title: "Event Organization"
          subtitle: "bringing people together"
          link: "https://chat.rockylinux.org/rocky-linux/channels/events"

    - id: "qa"
      title: "TESTING"
      subtitle: "if it's not tested, it's broken"
      options:
        - id: "bug-hunting"
          title: "Bug Hunting"
          subtitle: "finding the glitches"
          link: "https://github.com/rocky-linux/rocky/issues"
        - id: "test-automation"
          title: "Test Automation"
          subtitle: "automated quality assurance"
          link: "https://github.com/rocky-linux/testing"

    - id: "packaging"
      title: "PACKAGING"
      subtitle: "building the distribution"
      options:
        - id: "rpm-packaging"
          title: "RPM Packaging"
          subtitle: "creating packages"
          link: "https://github.com/rocky-linux/rpms"
        - id: "module-building"
          title: "Module Building"
          subtitle: "composing the distro"
          link: "https://chat.rockylinux.org/rocky-linux/channels/packaging"
    # Add more categories... 