export default {
  meta: {
    title: "What can I do for Rocky Linux?",
    description: "Find out how you can contribute to Rocky Linux"
  },
  common: {
    soundsAwesome: "Sounds awesome",
    notOnYourLife: "Not on your life"
  },
  home: {
    wantToHelp: "Want to help Rocky Linux? Tell me...",
    areaOfInterest: "What's your area of interest?",
    footer: {
      generatedBy: "Generated by",
      inspiredBy: "Inspired by"
    }
  },
  questions: {
    segue1: "Want to help Rocky Linux? Tell me...",
    segue2: "What's your area of interest?",
    design: {
      title: "DESIGN!",
      subtitle: "pixel ninjas",
      websites: {
        title: "Website Design",
        subtitle: "crafting user experiences"
      },
      graphics: {
        title: "Graphics Design",
        subtitle: "visual storytelling"
      },
      ux: {
        title: "UX Design",
        subtitle: "making things intuitive"
      }
    },
    coding: {
      title: "CODING",
      subtitle: "hacking the gibson",
      webdev: {
        title: "Web Development",
        subtitle: "building the web presence"
      },
      system: {
        title: "System Programming",
        subtitle: "core system development"
      },
      automation: {
        title: "Automation",
        subtitle: "making things efficient"
      }
    },
    documentation: {
      title: "DOCUMENTATION",
      subtitle: "wordsmithery",
      technical: {
        title: "Technical Writing",
        subtitle: "explaining the complex"
      },
      translation: {
        title: "Translation",
        subtitle: "breaking language barriers"
      }
    },
    community: {
      title: "COMMUNITY",
      subtitle: "connecting the dots"
    }
  }
} 