export default {
  meta: {
    title: "What can I do for Rocky Linux?",
    description: "Find out how you can contribute to Rocky Linux"
  },
  common: {
    soundsAwesome: "Sounds awesome",
    notOnYourLife: "Not on your life",
    easterEggs: [
      "Oh, you're one of those button smashers...",
      "Found the QA tester!",
      "Very funny. Hilarious even.",
      "Did that button hurt you somehow?",
      "Achievement unlocked: Button Masher"
    ],
    startOver: "Start over"
  },
  home: {
    wantToHelp: "Want to help Rocky Linux? Tell me...",
    areaOfInterest: "What's your area of interest?",
    footer: {
      generatedBy: "Generated by",
      inspiredBy: "Inspired by"
    }
  },
  questions: {
    segue1: "Want to help Rocky Linux? Tell me...",
    segue2: "What's your area of interest?",
    design: {
      title: "DESIGN!",
      subtitle: "pixel ninjas",
      websites: {
        title: "Website Design",
        subtitle: "crafting user experiences"
      },
      graphics: {
        title: "Graphics Design",
        subtitle: "visual storytelling"
      },
      ux: {
        title: "UX Design",
        subtitle: "making things intuitive"
      }
    },
    coding: {
      title: "CODING",
      subtitle: "hacking the gibson",
      webdev: {
        title: "Web Development",
        subtitle: "building the web presence"
      },
      system: {
        title: "System Programming",
        subtitle: "core system development"
      },
      automation: {
        title: "Automation",
        subtitle: "making things efficient"
      }
    },
    documentation: {
      title: "DOCUMENTATION",
      subtitle: "wordsmithery",
      technical: {
        title: "Technical Writing",
        subtitle: "explaining the complex"
      },
      translation: {
        title: "Translation",
        subtitle: "breaking language barriers"
      }
    },
    community: {
      title: "COMMUNITY",
      subtitle: "connecting the dots",
      advocacy: {
        title: "Advocacy",
        subtitle: "spreading the word"
      },
      support: {
        title: "User Support",
        subtitle: "helping others succeed"
      },
      events: {
        title: "Event Organization",
        subtitle: "bringing people together"
      }
    },
    qa: {
      title: "TESTING",
      subtitle: "if it's not tested, it's broken",
      bugHunting: {
        title: "Bug Hunting",
        subtitle: "finding the glitches"
      },
      testAutomation: {
        title: "Test Automation",
        subtitle: "automated quality assurance"
      }
    },
    packaging: {
      title: "PACKAGING",
      subtitle: "building the distribution",
      rpm: {
        title: "RPM Packaging",
        subtitle: "creating packages"
      },
      modules: {
        title: "Module Building",
        subtitle: "composing the distro"
      }
    }
  }
} 