name: Deploy AskNot-Rocky
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v3

    - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install dependencies
      run: npm install

    - name: build site
      run: npm run build

    - name: Build Compute Package
      uses: fastly/compute-actions/build@v11
      with:
        project_directory: compute-js

    - name: Deploy Compute Package
      uses: fastly/compute-actions/deploy@v11
      with:
        project_directory: compute-js
        comment: "Deployed via GitHub Actions for ${{ github.head_ref }}.${{ github.sha }}"
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}

    - name: Notify documentation channel about deployment Success
      uses: mattermost/action-mattermost-notify@master
      if: success() && !cancelled()
      with:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: web
        TEXT: |
          [join.rockylinux.org Deployment](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) was completed :white_check_mark:
        MATTERMOST_USERNAME: "Github"

    - name: Notify documentation channel about deployment Failure
      uses: mattermost/action-mattermost-notify@master
      if: failure() && !cancelled()
      with:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: web
        TEXT: |
          [join.rockylinux.org Deployment](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed :x:
        MATTERMOST_USERNAME: "Github"
