name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      id: lint
      run: npm run lint
      continue-on-error: true

    - name: Create Status Comment
      if: github.event_name == 'pull_request' && steps.lint.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          const message = `## Lint Results\n\n❌ ESLint check failed. Please fix the linting issues in your code.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

    - name: Check for failures
      if: steps.lint.outcome == 'failure'
      run: exit 1 