name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      id: test
      run: npm run test:precommit
      continue-on-error: true

    - name: Create Status Comment
      if: github.event_name == 'pull_request' && steps.test.outcome == 'failure'
      uses: actions/github-script@v7
      with:
        script: |
          const message = `## Test Results\n\n❌ Unit tests failed. Please check the test output for details.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

    - name: Check for failures
      if: steps.test.outcome == 'failure'
      run: exit 1 